#!/usr/bin/env python3
"""Peacock-style worktree colours for herdr.

Every worktree with a port (worktree-port.sh) gets a colour: review worktrees (review-*)
purples, work worktrees blues/teals, 5 shades each, picked by port so worktrees open at the
same time differ.
  - focused worktree: accent (active tab, focus) and the tab bar tinted with it
  - every worktree: its workspace name in its colour, in the Spaces and Agents lists
  - anything else: the normal theme

herdr has no per-workspace colours, so this writes a generated config: the real
~/.config/herdr/config.toml plus these overrides, at $HERDR_CONFIG_PATH
(~/.config/herdr/config.generated.toml, set in .zshenv). It runs on workspace focus,
worktree create/remove and herdr startup (plugin kris-tools), and reloads herdr only when
the output changed. The name colours go onto lines in config.toml marked "# worktree-colors".

Usage: worktree-theme.py [--reload] [focused workspace id]   (default: ask herdr)
  --reload  reload herdr even if nothing changed: `herdr-reload` after editing config.toml
"""
import json
import os
import subprocess
import sys

HOME = os.path.expanduser("~")
SOURCE = os.path.join(HOME, ".config/herdr/config.toml")
OUT = os.environ.get("HERDR_CONFIG_PATH") or os.path.join(HOME, ".config/herdr/config.generated.toml")
REGISTRY = os.path.join(os.environ.get("XDG_STATE_HOME") or os.path.join(HOME, ".local/state"), "herdr/ports")
HERDR = os.environ.get("HERDR_BIN_PATH") or "herdr"
MARK = "# worktree-colors"

SHADES = {
    "review": ["#cba6f7", "#a684ff", "#e8b4ff", "#8f6fdc", "#d68ff2"],
    "work": ["#89b4fa", "#74c7ec", "#94e2d5", "#89dceb", "#6c9ef8"],
}
# Catppuccin Mocha tab bar background the tint is mixed into
PANEL_BG = "#181825"


def herdr(*args):
    try:
        out = subprocess.run([HERDR, *args], capture_output=True, text=True, timeout=5).stdout
        return json.loads(out).get("result", {})
    except Exception:
        return {}


def mix(color, base, amount):
    c = [int(color[i:i + 2], 16) for i in (1, 3, 5)]
    b = [int(base[i:i + 2], 16) for i in (1, 3, 5)]
    return "#" + "".join(f"{round(b[i] + (c[i] - b[i]) * amount):02x}" for i in range(3))


def worktree_colours():
    """workspace id -> (label, colour) for open worktrees that have a port."""
    ports = {}
    try:
        with open(REGISTRY) as f:
            for line in f:
                port, _, path = line.rstrip("\n").partition("\t")
                if port.isdigit() and os.path.isdir(path):
                    ports[path] = int(port)
    except FileNotFoundError:
        return {}
    labels = {w["workspace_id"]: w.get("label", "") for w in herdr("workspace", "list").get("workspaces", [])}
    result, seen_repos = {}, set()
    for path in ports:
        listing = herdr("worktree", "list", "--cwd", path)
        repo = listing.get("source", {}).get("repo_root")
        if repo in seen_repos:
            continue
        seen_repos.add(repo)
        for wt in listing.get("worktrees", []):
            ws, wt_path = wt.get("open_workspace_id"), wt.get("path")
            if not ws or wt_path not in ports or ws not in labels:
                continue
            kind = "review" if os.path.basename(wt_path).startswith("review-") else "work"
            shades = SHADES[kind]
            result[ws] = (labels[ws], shades[(ports[wt_path] - 3100) % len(shades)])
    return result


def generate(focused):
    with open(SOURCE) as f:
        lines = f.read().splitlines()
    colours = worktree_colours()

    # Name colours: style the "workspace" token on marked rows (herdr allows 16 rules per token)
    rules = [f"{{ equals = {json.dumps(label)}, fg = \"{colour}\" }}" for label, colour in list(colours.values())[:16]]
    styled = f'{{ token = "workspace", rules = [{", ".join(rules)}] }}' if rules else '"workspace"'
    lines = [l.replace('"workspace"', styled, 1) if MARK in l else l for l in lines]

    # Focused worktree: accent and a tinted tab bar. Not active_row_bg: herdr uses it for the
    # focused Agent row too, and a coloured block there is too loud.
    if focused in colours:
        colour = colours[focused][1]
        overrides = [
            f'accent = "{colour}"',
            f'panel_bg = "{mix(colour, PANEL_BG, 0.22)}"',
        ]
        if "[theme.custom]" in lines:
            i = lines.index("[theme.custom]")
            lines[i + 1:i + 1] = overrides
        else:
            lines += ["", "[theme.custom]  # added by worktree-theme.py", *overrides]

    text = "# GENERATED by herdr/scripts/worktree-theme.py from config.toml. Edit config.toml, not this.\n" \
        + "\n".join(lines) + "\n"
    try:
        with open(OUT) as f:
            if f.read() == text:
                return False
    except FileNotFoundError:
        pass
    tmp = OUT + ".tmp"
    with open(tmp, "w") as f:
        f.write(text)
    os.replace(tmp, OUT)
    return True


def main():
    args = sys.argv[1:]
    force = "--reload" in args
    args = [a for a in args if a != "--reload"]
    event = json.loads(os.environ.get("HERDR_PLUGIN_EVENT_JSON") or "{}")
    focused = args[0] if args else event.get("data", {}).get("workspace_id") or next(
        (w["workspace_id"] for w in herdr("workspace", "list").get("workspaces", []) if w.get("focused")), None)
    if (generate(focused) or force) and os.environ.get("HERDR_CONFIG_PATH") == OUT:
        subprocess.run([HERDR, "server", "reload-config"], capture_output=True, timeout=5)


if __name__ == "__main__":
    main()
